name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Grant execute permissions to the script
        run: chmod +x ./http_response_query.sh

      - name: Run site availability check
        run: ./http_response_query.sh
